apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: third-middleware
  template:
    metadata:
      labels:
        app: third-middleware
    spec:
      containers:
        - name: third-middleware
          image: uhub.service.ucloud.cn/entropypool/third-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/ThirdMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV_RECAPTCHA_REQUEST_PROXY
              valueFrom:
                configMapKeyRef:
                  name: recaptcha-proxy-environment
                  key: environment.recaptcha_proxy
            - name: ENV_REQUEST_PROXY
              valueFrom:
                configMapKeyRef:
                  name: request-proxy-environment
                  key: environment.request_proxy
      volumes:
        - name: service-config
          configMap:
            name: third-middleware-config
            items:
              - key: service-conf
                path: ThirdMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: third-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50520
      targetPort: 50520
    - name: grpc
      port: 50521
      targetPort: 50521
    - name: healthz
      port: 50522
      targetPort: 50522
    - name: prometheus
      port: 50523
      targetPort: 50523
  selector:
    app: third-middleware
